/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef RTCPP_H
#define RTCPP_H

#include "datasource.h"
#include "datasink.h"

namespace rtcpp {
    std::string AnalyzeRTPDump(DataSource& dataStream);
    void TransformRTPDump(DataSource& istream, DataSink& ostream, const std::string& jsonCfg);
}

#endif
